### ISSUE TITLE
Vibrance Gui not working for R6 Siege

### ISSUE THREAD

**Issue by DieQuelle** [juvlarN/vibranceGUI#29]
Hey,

at first thanks for this reall needed tool. I used it for csgo a while but now im playing r6 siege.

One Problem is: It won't get detected. So first thing happens already here. (Tried running gui as admin/normal local admin user) no difference.

I added it manually by adding the .exe - still not working. 

Second thing to try if it works I configured my Windows Vibrance level to maximum (300) and nothing happens so maybe there is already a problem @ trying to activate the vibrance model.

Im running a GTX 970 Strix OC from Asus with following Drivers and Devices:
Game Ready Driver: 376.33 Date 12/14/2016

1. BenQ XL4211Z @ 144hz 1920x1080
2. Dell UH42..somehow @60hz 1920x1200

Maybe you could help me resolving this issue.

**Comment by juvlarN** [comment]
Yeah you have AMD drivers left over on your computer.
Clean up your drivers. Especially atiadlxx.dll and atiadlxy.dll in your Windows folder (move/rename/delete).

**Comment by DieQuelle** [comment]
Okay i fixed that with the amd clean up utility.

No I cant bring back the dynamic mode? Any Idea?

**Comment by juvlarN** [comment]
What do you mean exactly?
When you can set the value to 300%, you're running the AMD version. Which means atiadlxx.dll or atiadlxy.dll are still present in your Windows folder. For Nvidia, you will need nvapi.dll in your Windows folder. It should come with  a clean install of the Nvidia drivers. 

For the Nvidia version, you can set the vibrance value from 50% to 100% because that is limited by the driver. This can not be forced to higher values.

**Comment by DieQuelle** [comment]
The GUI looks like that: [http://puu.sh/ts7lq/0c4681140a.png](url)


Im searching for files of my old ATI Card but i dont want to move ati*.dll from the windows folders.
Cant understand why the utility is so much crap.

**Comment by juvlarN** [comment]
The screenshot looks fine to me. You did not properly describe what is not working though. "No I cant bring back the dynamic mode?" ... do you mean the Beta version of vibranceGUI? The screenshot shows the version from the website and not the Beta from my Twitter. 

I never told you to delete ati*.dll files lol. I told you two specific files (the API of AMD driver), which when you are using nvidia, should never be used by any application.

**Comment by DieQuelle** [comment]
Okay nevermind.

So for everyone who is bugged with ATI Files:

**Use with Caution**

Run Powershell @ C:\Windows
> Get-ChildItem -Path V:\Myfolder -Filter CopyForbuild.bat -Recurse -ErrorAction SilentlyContinue -Force

Check if there are ANY needed files.
> del ati* @ each path which is shown.

Sorry for that stable / beta fail thought I got the "newes" .exe.

Works now as expected.

Thank you for your fast help 👍
